apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-smtp
  labels:
    app: fake-smtp
spec:
  selector:
    matchLabels:
      app: fake-smtp
  template:
    metadata:
      labels:
        app: fake-smtp
    spec:
      containers:
        - name: fake-smtp
          image: reachfive/fake-smtp-server:latest
          ports:
            - containerPort: 1080
              protocol: TCP
            - containerPort: 1025
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: fake-smtp-service
spec:
  type: NodePort
  selector:
    app: fake-smtp
  ports:
    - port: 1080
      protocol: TCP
      name: list-api
    - port: 1025
      protocol: TCP
      name: smtp
